### ISSUE TITLE
Slight change to get it working for me

### ISSUE THREAD

**Issue by AlanMcCann** [aiming-pro/verte-vue3#1]
I had to make the following changes to get it working
```
import Verte from 'verte-vue3';
import 'verte-vue3/dist/verte.css';
import app from './App.vue'
const app = createApp(app)
app.component(Verte)
```

**Comment by jf908** [comment]
Thanks, I have fixed the import strings in the docs f039be476ae830c4512390470060e3ca3203168d.

If this issue is about needing the `app.component(Verte)` line, then any vue component has to be [registered](https://vuejs.org/guide/components/registration.html) before it can be used. The example in verte's docs just uses local registration.
